language: node_js
sudo: required
node_js: '8'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
    - node_modules    
    - bower_components
install: 
- npm install -g yarn
- yarn add global bower
- yarn add global polymer-cli
- node -v
- polymer --version
- yarn --version
- yarn install
- bower install
before_script:
- polymer lint
script:
- polymer build --verbose
notifications:
  email: false